### ISSUE TITLE
Support 64 bit ObjectIds

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#121]
According to https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm

> If the layer objectIdField does not have a length property or the length property is set to 4, the objectIdField is 32-bit. If the objectIdField has a length of 8, the objectIdField is 64-bit.

Can you add support for specifying the length of the ObjectId? Maybe by allowing the `idFieldLength` in the metadata?

**Comment by rgwozdz** [comment]
@jkerr5 thanks for posting this and providing the above link.  I will put together a PR for 64 bit support in both FeatureServer and Winnow.

**Comment by rgwozdz** [comment]
Perhaps we could have the OBJECTID _always_ be 64 bit?

**Comment by jkerr5** [comment]
That would be fine with me.

**Comment by jkerr5** [comment]
@rgwozdz any thoughts on when this might make it into a release?

**Comment by rgwozdz** [comment]
Hopefully relatively soon.  I'm juggling it with a few other things.  It's going to require a companion update/release of Winnow and then testing on all the ArcGIS clients, so it's a bit of work to coordinate - unless someone else wants the PR, I probably can't get to it until end of the week.

**Comment by jkerr5** [comment]
Thanks for the update @rgwozdz

**Comment by rgwozdz** [comment]
@jkerr5 - I'm going to assume the max value for the OBJECTID is the upper limit for an *signed* 64 bit integer, since there are some references to 32 bit OBJECTIDs having a [max value of the *signed* type](http://desktop.arcgis.com/en/arcmap/10.3/manage-data/using-sql-with-gdbs/object-id.htm).

**Comment by rgwozdz** [comment]
@jkerr5 - I'm realizing there is an impediment to implementation.  JavaScript represents numbers using IEEE-754 double-precision (64 bit) format. It turns out that that give sus only 53 bits precision, which is around fifteen to sixteen decimal digits.  When you get to numbers that large or larger, you end up getting approximations:
```
var bigNumber = 9023372036854775807
console.log(bigNumber); // 9023372036854776000
```
So while the link you provide indicates ArcGIS support of 64-bit OBJECTIDs,  Koop can't readily deliver them due to limitations of JavaScript.  A provider could supply a 64-bit integer as a string, but it would have to be converted to an integer prior to serving it to ArcGIS clients (as OBJECTIDs appear to still have to be integers for ArcGIS clients).  That conversion could lead to a loss of precision, with the potential result being duplicate OBJECTIDs.

One way forward would be to have FeatureServer set the OBJECTID length to 8 (indicating 64-bit) but print a warning if a provider pushed through an OBJECTID that was greater that the unsigned 53-bit max value (9007199254740991).  

How many digits where you hoping to support?  Wondering if a max OBJECTID value of 9007199254740991 will suit your needs prior to undertaking the work.

**Comment by jkerr5** [comment]
The 53-bit max value of 9007199254740991 would be good. Anything more than
the 32-bits we have now would be great :)

**Comment by jkerr5** [comment]
Hi @rgwozdz Any update on an ETA for this? We are working a project that needs bigger OBJECTIDs so were hoping this would make it in soon. Thanks.

**Comment by rgwozdz** [comment]
Hey @jkerr5  - sorry, I've been consumed with a few other big projects so I haven't been able to get to it.  I may be freed up starting next week.  Sorry, if you guys want to start your own PR, feel free.  But it's still in my queue.

**Comment by jkerr5** [comment]
That's unfortunate to hear. I posted a question to the community https://community.esri.com/message/821822-can-arcgis-pro-support-64-bit-objectids

**Comment by rgwozdz** [comment]
Ideally, we would have an example feature service that implements the objectIdField length property and pumps out 64 bit integer IDs.  Then we could analyze the responses, test in clients, and simulate the behavior in Koop.

**Comment by rgwozdz** [comment]
@jkerr5 - closing this given the response at 
https://community.esri.com/message/821822-can-arcgis-pro-support-64-bit-objectids
